from gi.repository import GObject, Gio

class MixerStream(GObject.Object):
    def get_gicon(self) -> Gio.ThemedIcon: ...
    def get_volume(self) -> int: ...
    def set_volume(self, volume: int) -> None: ...
    def get_is_muted(self) -> bool: ...
    def set_is_muted(self, muted: bool) -> None: ...
    def push_volume(self) -> bool: ...

class MixerControl(GObject.Object):
    def __init__(self, name: str) -> None: ...
    def open(self) -> bool: ...
    def get_vol_max_norm(self) -> int: ...
    def get_default_sink(self) -> MixerStream | None: ...
    def get_default_source(self) -> MixerStream | None: ...

class MixerSinkInput(MixerStream): ...
class MixerSink(MixerStream): ...
class MixerSource(MixerStream): ...
class MixerSourceOutput(MixerStream): ...
